//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DosyaYonetimPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int Id { get; set; }
        public string fileName { get; set; }
        public int fileTypeId { get; set; }
        public int fileGroupId { get; set; }
        public int fileUploaderId { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
