//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DosyaYonetimPortalı.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DosyaYonetimPortaliEntities1 : DbContext
    {
        public DosyaYonetimPortaliEntities1()
            : base("name=DosyaYonetimPortaliEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authority> authorities { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<filetype> filetypes { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
